site_name: Data Models

theme:
  name: material
  icon:
    logo: material/database-sync
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top # show a "navigate to top" button when scrolling
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Dark Mode
      primary: blue grey
      accent: black
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Light Mode
      primary: brown
      accent: blue

# copyright: Copyright &copy; 2024 TMRSM Ltd