name: deploy 

on:
  push:
    branches:
      - main
    paths:
    - 'datam/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: 'datam/'
          sparse-checkout-cone-mode: false

      - name: 'Display directory content'
        shell: bash
        run: |
          pwd
          ls -l
          cd datam
          pwd
          ls -l

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 'Cache'
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: cd datam
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force