name: 'publish DATAM mkdocs to github.io'

on:
  push:
    branches:
      - main
    paths:
    - 'datam/**'

env:
  CACHE_ID: date --utc '+%V'

# Allows you to run this workflow manually from the Actions tab
#workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: 'datam/'
          sparse-checkout-cone-mode: false

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 'Cache'
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.CACHE_ID }}
          path: .cache
          restore-keys:
            mkdocs-material-

      - name: 'mkdocs deploy'
        shell: bash
        run: |
          pwd
          ls -l
          cd datam
          pwd
          ls -l
          pip install mkdocs-material
          mkdocs gh-deploy --force
