site_name: TMRSM Docs

theme:
  name: material
  icon:
    logo: material/database-sync
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.expand
    - navigation.top # show a "navigate to top" button when scrolling
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Dark Mode
      primary: blue grey
      accent: black
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Light Mode
      primary: deep purple
      accent: purple

nav:
  - index.md
  - Data:
    - data/lakehouse.md
  - Insurance:
    - insurance/Glossary.md
    - insurance/ClassOfBusiness.md
  - Finance:
    - finance/SFT.md
  - Energy:
    - energy/mhhs.md
    - energy/MHHS/CoS.md

plugins: 
  - search
  - mermaid2

markdown_extensions:
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

copyright: Copyright &copy; 2024 TMRSM Ltd
